import crypto from 'node:crypto';
import { detectFixtureFailure } from './detector';
import { diagnose } from './ai';
import { fingerprintFailure } from './evidence';
import { createRepairPlan } from './policy';
import { applyRepair } from './repair';
import { validateRepair } from './validation';
import { buildGitPlan, createLocalBranch, pushBranch } from './git';
import { createIssue, createPullRequest } from './github';
import type { GuardianConfig, GuardianRun } from './types';
export async function runGuardian(config: GuardianConfig): Promise<GuardianRun> { const run: GuardianRun = { runId: crypto.randomUUID(), status: 'PASS', environment: config.mode, commit: 'unknown' }; const evidence = await detectFixtureFailure(config); if (!evidence) return run; run.status = 'DETECTED'; run.evidence = evidence; run.fingerprint = fingerprintFailure(evidence); if (config.mode === 'prototype' && config.githubWrite) { const issue = await createIssue(config, `[Guardian] ${evidence.failure}`, `## Guardian Run\n${run.runId}\n\n## Failure\n${evidence.failure}\n\n## Evidence\n${JSON.stringify(evidence, null, 2)}\n\n## Fingerprint\n${run.fingerprint}\n\n## Environment\n${evidence.environment}\n\n## Detected At\n${evidence.detectedAt}`, run.fingerprint); run.status = 'ISSUE_CREATED'; console.log(`Issue: ${issue.html_url}`); } run.diagnosis = await diagnose(config, evidence); run.status = 'DIAGNOSED'; run.repairPlan = createRepairPlan(config, run.diagnosis); run.status = 'REPAIR_PLANNED'; console.log(JSON.stringify({ repairPlan: run.repairPlan }, null, 2)); await applyRepair(config, run.repairPlan); run.status = 'REPAIRED'; const proposedPath = config.mode === 'dry-run' ? run.repairPlan.operations.find((operation) => operation.file === config.fixturePath || operation.file.endsWith('project-reference.json'))?.newValue : undefined; run.validation = await validateRepair(config, proposedPath); if (!run.validation.passed) { run.status = 'VALIDATION_FAILED'; return run; } run.git = await buildGitPlan(run.fingerprint, evidence, run.diagnosis, run.repairPlan); if (config.mode === 'dry-run') { run.status = 'REQUIRES_HUMAN_REVIEW'; return run; } if (!config.githubWrite) { run.status = 'REQUIRES_HUMAN_REVIEW'; return run; } await createLocalBranch(run.git); await pushBranch(run.git); const pullRequest = await createPullRequest(config, run.git.branch, run.git.pullRequestTitle, run.git.pullRequestBody); console.log(`Pull request: ${pullRequest.html_url}`); run.status = 'PR_CREATED'; run.status = 'REQUIRES_HUMAN_REVIEW'; return run; }